id: P008248
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:10:37.521650
source_metadata:
  id: bdr:W29105
  title: མན་ངག་ཡིག་ཆུང་སྣ་ཚོགས
  author: ''
  volumes:
    6c8610e7521f4e5a969aed35c832fa65:
      image_group_id: I1PD386
      title: ''
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
